# Generated by Django 3.0.4 on 2020-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bottom',
            field=models.IntegerField(max_length=120, null=True),
        ),
    ]
