# Generated by Django 3.0.4 on 2020-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize', '0003_auto_20200402_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='right',
            field=models.IntegerField(null=True),
        ),
    ]
