# Generated by Django 3.0.4 on 2020-04-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='x',
        ),
        migrations.RemoveField(
            model_name='image',
            name='y',
        ),
        migrations.AddField(
            model_name='image',
            name='bottom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='right',
            field=models.IntegerField(null=True),
        ),
    ]
