# Generated by Django 3.0.4 on 2020-03-30 11:46

from django.db import migrations, models
import django.db.models.deletion
import file_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_auto_20200316_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='', validators=[file_app.validators.validate_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileMimeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MimeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.FileMimeType')),
            ],
        ),
        migrations.CreateModel(
            name='TypeArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typearea', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.Type')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='filemimetype',
            name='file_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.FileType'),
        ),
        migrations.AddField(
            model_name='filemimetype',
            name='mime_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.MimeType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='mime_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.MimeType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.Type'),
        ),
    ]
