# Generated by Django 3.0.4 on 2020-04-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_auto_20200330_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typearea',
            old_name='typearea',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='asset',
            name='mime_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file_app.MimeType'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file_app.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='file_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file_app.FileMimeType'),
        ),
        migrations.AlterField(
            model_name='typearea',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file_app.Type'),
        ),
    ]
