# Generated by Django 3.0.4 on 2020-04-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_auto_20200406_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetype',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mimetype',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='type',
            name='file_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.FileType'),
        ),
        migrations.AlterField(
            model_name='typearea',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.Type'),
        ),
    ]
